document.addEventListener('DOMContentLoaded',async()=>{
  let cases=await apiRequest('/api/cases');const patients=await apiRequest('/api/patients'),pmap=Object.fromEntries(patients.map(p=>[p.PatientID,p])),tbody=document.getElementById('casesTableBody'),search=document.getElementById('caseSearch'),type=document.getElementById('caseTypeFilter'),status=document.getElementById('caseStatusFilter');
  document.getElementById('casePatient').insertAdjacentHTML('beforeend',patients.map(p=>`<option value="${p.PatientID}">PT-${p.PatientID} — ${UI.escapeHtml(p.Name)}</option>`).join(''));
  const render=()=>{const term=search.value.toLowerCase(),filtered=cases.filter(c=>`${c.CaseID} ${pmap[c.PatientID]?.Name||''} ${c.PoliceReferenceNo}`.toLowerCase().includes(term)&&(!type.value||c.CaseType===type.value)&&(!status.value||c.Status===status.value));document.getElementById('caseCount').textContent=filtered.length;tbody.innerHTML=filtered.length?filtered.map(c=>`<tr><td class="record-id">CF-${c.CaseID}</td><td><strong>${UI.escapeHtml(pmap[c.PatientID]?.Name||'Unknown')}</strong><br><small class="text-muted">PT-${c.PatientID}</small></td><td>${UI.escapeHtml(c.CaseType)}</td><td>${UI.formatDate(c.IncidentDate)}<br><small class="text-muted">${UI.escapeHtml(c.Place)}</small></td><td class="mono">${UI.escapeHtml(c.PoliceReferenceNo)}</td><td>${UI.escapeHtml(c.AssignedDoctor)}</td><td>${UI.statusBadge(c.Status)}</td><td class="text-end text-nowrap"><button class="btn btn-sm btn-outline-secondary qr-case" data-id="${c.CaseID}">QR</button> <button class="btn btn-sm btn-outline-primary view-case" data-id="${c.CaseID}">Track</button></td></tr>`).join(''):UI.emptyRow(8);};
  [search,type,status].forEach(x=>x.addEventListener('input',render));
  tbody.addEventListener('click',e=>{const q=e.target.closest('.qr-case'),b=e.target.closest('.view-case');if(q){const c=cases.find(x=>x.CaseID===Number(q.dataset.id));showTrackingQr({kind:'case',id:c.CaseID,label:`Case CF-${c.CaseID} · ${c.CaseType}`});return;}if(!b)return;const c=cases.find(x=>x.CaseID===Number(b.dataset.id)),p=pmap[c.PatientID];document.getElementById('caseDrawerTitle').textContent=`Case CF-${c.CaseID}`;document.getElementById('caseDrawerBody').innerHTML=`<div class="stat-inline mb-4"><div class="stat-pill"><span>Patient</span><strong>${UI.escapeHtml(p?.Name||'Unknown')}</strong></div><div class="stat-pill"><span>Type</span><strong>${UI.escapeHtml(c.CaseType)}</strong></div><div class="stat-pill"><span>Status</span><strong>${UI.escapeHtml(c.Status)}</strong></div></div>
  <section class="official-card mb-3"><div class="card-body"><h3 class="section-heading">Case particulars</h3><div class="row g-3"><div class="col-6"><small class="text-muted">Incident date</small><div class="fw-semibold">${UI.formatDate(c.IncidentDate)}</div></div><div class="col-6"><small class="text-muted">Place</small><div class="fw-semibold">${UI.escapeHtml(c.Place)}</div></div><div class="col-6"><small class="text-muted">Police reference</small><div class="fw-semibold mono">${UI.escapeHtml(c.PoliceReferenceNo)}</div></div><div class="col-6"><small class="text-muted">Assigned officer</small><div class="fw-semibold">${UI.escapeHtml(c.AssignedDoctor)}</div></div></div></div></section>
  <section class="official-card mb-3"><div class="card-body"><h3 class="section-heading">Status tracker</h3><div class="step-tracker"><div class="step done"><small>Step 1</small><strong>Registered</strong></div><div class="step done"><small>Step 2</small><strong>Exam / PM</strong></div><div class="step ${c.Status==='Completed'?'done':'current'}"><small>Step 3</small><strong>Report</strong></div><div class="step ${c.Status==='Completed'?'done':''}"><small>Step 4</small><strong>Closed</strong></div></div></div></section>
  <button class="btn btn-outline-primary w-100" onclick="showTrackingQr({kind:'case',id:${c.CaseID},label:'Case CF-${c.CaseID}'})">Generate case QR label</button>`;bootstrap.Offcanvas.getOrCreateInstance(document.getElementById('caseDrawer')).show();});
  FormValidation.bindBootstrapValidation(document.getElementById('caseForm'),async(fd,form)=>{const r=Object.fromEntries(fd.entries());r.PatientID=Number(r.PatientID);r.CaseTypeID=document.getElementById('caseType').selectedIndex;r.RegisteredBy=42;const saved=await apiRequest('/api/cases',{method:'POST',body:r});cases.unshift(saved);render();form.reset();form.classList.remove('was-validated');bootstrap.Modal.getInstance(document.getElementById('caseModal')).hide();UI.toast(`Case CF-${saved.CaseID} created.`);});
  render();
});
