document.addEventListener('DOMContentLoaded',async()=>{
  const cases=(await apiRequest('/api/cases')).filter(c=>c.CaseType!=='Postmortem'),select=document.getElementById('clinicalCase'),injuries=[];let selected='';
  select.insertAdjacentHTML('beforeend',cases.map(c=>`<option value="${c.CaseID}">CF-${c.CaseID} — ${UI.escapeHtml(c.CaseType)}</option>`).join(''));
  document.querySelectorAll('.body-region').forEach(r=>r.onclick=()=>{document.querySelectorAll('.body-region').forEach(x=>x.classList.remove('selected'));r.classList.add('selected');selected=r.dataset.part;const b=document.getElementById('selectedBodyPartBadge');b.textContent=selected;b.className='case-seal status-success';});
  const render=()=>document.getElementById('injuryTable').innerHTML=injuries.length?injuries.map((x,i)=>`<tr><td>${UI.escapeHtml(x.BodyPart)}</td><td>${UI.escapeHtml(x.InjuryType)}</td><td>${UI.statusBadge(x.Severity)}</td><td>${UI.escapeHtml(x.Description)}</td><td><button type="button" class="btn btn-sm btn-outline-danger remove-injury" data-i="${i}">Remove</button></td></tr>`).join(''):UI.emptyRow(5,'No injury details added.');
  document.getElementById('addInjury').onclick=()=>{const d=document.getElementById('injuryDescription').value.trim();if(!selected)return UI.toast('Select a body region first.','warning');if(!d)return UI.toast('Enter an injury description.','warning');injuries.push({BodyPart:selected,InjuryType:document.getElementById('injuryType').value,Severity:document.getElementById('injurySeverity').value,Description:d});document.getElementById('injuryDescription').value='';render();UI.toast(`${selected} injury detail added.`);};
  document.getElementById('injuryTable').onclick=e=>{const b=e.target.closest('.remove-injury');if(b){injuries.splice(Number(b.dataset.i),1);render();}};
  FormValidation.bindBootstrapValidation(document.getElementById('clinicalForm'),async(fd,form)=>{const saved=await apiRequest('/api/examinations',{method:'POST',body:{CaseID:Number(fd.get('CaseID')),DoctorID:Number(fd.get('DoctorID')),Date:fd.get('Date'),ReferralType:fd.get('ReferralType'),DoctorNotes:fd.get('DoctorNotes'),Status:'Draft',InjuryDetails:injuries}});UI.toast(`Clinical examination EX-${saved.ExaminationID} saved.`);form.classList.remove('was-validated');});
  document.getElementById('saveClinicalDraft').onclick=()=>UI.toast('Draft stored locally for later API sync.');render();
});
