document.addEventListener('DOMContentLoaded',async()=>{
  let evidence=await apiRequest('/api/evidence'),custody=await apiRequest('/api/custody');const cases=await apiRequest('/api/cases'),samples=await apiRequest('/api/lab-samples'),tests=await apiRequest('/api/lab-tests'),search=document.getElementById('evidenceSearch'),status=document.getElementById('evidenceStatusFilter');
  document.getElementById('evidenceCase').insertAdjacentHTML('beforeend',cases.map(c=>`<option value="${c.CaseID}">CF-${c.CaseID} — ${UI.escapeHtml(c.CaseType)}</option>`).join(''));
  const populate=()=>{const o=evidence.map(e=>`<option value="${e.EvidenceID}">EV-${e.EvidenceID} — ${UI.escapeHtml(e.EvidenceType)}</option>`).join('');document.getElementById('custodyEvidence').innerHTML='<option value="">Select evidence</option>'+o;document.getElementById('timelineEvidence').innerHTML=o;};
  const renderEvidence=()=>{const term=search.value.toLowerCase(),f=evidence.filter(e=>`${e.EvidenceID} ${e.CaseID} ${e.EvidenceType} ${e.StorageLocation}`.toLowerCase().includes(term)&&(!status.value||e.Status===status.value));document.getElementById('evidenceTable').innerHTML=f.length?f.map(e=>`<tr><td class="record-id">EV-${e.EvidenceID}</td><td class="record-id">CF-${e.CaseID}</td><td>${UI.escapeHtml(e.EvidenceType)}</td><td>${UI.formatDate(e.CollectionDate)}<br><small class="text-muted">${UI.escapeHtml(e.Location)}</small></td><td>${UI.escapeHtml(e.LabName||'—')}</td><td>${UI.escapeHtml(e.StorageLocation)}</td><td>${UI.statusBadge(e.Status)}</td><td class="text-end"><button class="btn btn-sm btn-outline-primary evidence-qr" data-id="${e.EvidenceID}">Generate QR</button></td></tr>`).join(''):UI.emptyRow(8);};
  const renderTimeline=()=>{const id=Number(document.getElementById('timelineEvidence').value),logs=custody.filter(x=>x.EvidenceID===id).sort((a,b)=>new Date(b.TransferDate)-new Date(a.TransferDate));document.getElementById('custodyTimeline').innerHTML=logs.length?logs.map(x=>`<div class="timeline-item"><strong>${UI.escapeHtml(x.FromLocation)} → ${UI.escapeHtml(x.ToLocation)}</strong><span>${new Date(x.TransferDate).toLocaleString('en-GB')} · ${UI.escapeHtml(x.StaffName)}<br>${UI.escapeHtml(x.Remarks)}</span></div>`).join(''):'<p class="text-muted">No custody transfers recorded.</p>';};
  document.getElementById('sampleTable').innerHTML=samples.map(s=>`<tr><td class="record-id">SP-${s.SampleID}</td><td class="record-id">EV-${s.EvidenceID}</td><td>${UI.escapeHtml(s.SampleType)}</td><td>${UI.formatDate(s.CollectedDate)}</td></tr>`).join('');
  document.getElementById('testTable').innerHTML=tests.map(t=>`<tr><td class="record-id">LT-${t.TestID}</td><td class="record-id">SP-${t.SampleID}</td><td>${UI.escapeHtml(t.TestType)}</td><td>${UI.formatDate(t.TestDate)}</td><td>${UI.escapeHtml(t.Result)}</td><td>${UI.statusBadge(t.Status)}</td></tr>`).join('');
  [search,status].forEach(x=>x.addEventListener('input',renderEvidence));document.getElementById('timelineEvidence').onchange=renderTimeline;
  document.getElementById('evidenceTable').onclick=e=>{const b=e.target.closest('.evidence-qr');if(b){const item=evidence.find(x=>x.EvidenceID===Number(b.dataset.id));showTrackingQr({kind:'evidence',id:item.EvidenceID,label:`Evidence EV-${item.EvidenceID} · ${item.EvidenceType}`});}};
  FormValidation.bindBootstrapValidation(document.getElementById('evidenceForm'),async(fd,form)=>{const r=Object.fromEntries(fd.entries());r.CaseID=Number(r.CaseID);r.EvidenceTypeID=document.getElementById('evidenceType').selectedIndex;r.Status=r.LabName?'In Laboratory':'Stored';const saved=await apiRequest('/api/evidence',{method:'POST',body:r});evidence.unshift(saved);populate();renderEvidence();renderTimeline();form.reset();form.classList.remove('was-validated');bootstrap.Modal.getInstance(document.getElementById('evidenceModal')).hide();showTrackingQr({kind:'evidence',id:saved.EvidenceID,label:`Evidence EV-${saved.EvidenceID} · ${saved.EvidenceType}`});});
  FormValidation.bindBootstrapValidation(document.getElementById('custodyForm'),async(fd,form)=>{const r=Object.fromEntries(fd.entries());r.EvidenceID=Number(r.EvidenceID);r.StaffID=31;r.TransferDate=new Date().toISOString();const saved=await apiRequest('/api/custody',{method:'POST',body:r});custody.unshift(saved);document.getElementById('timelineEvidence').value=String(saved.EvidenceID);renderTimeline();form.reset();form.classList.remove('was-validated');UI.toast('Custody transfer recorded.');});
  document.getElementById('newSampleButton').onclick=()=>UI.toast('Connect this action to POST /api/lab-samples.','warning');document.getElementById('newTestButton').onclick=()=>UI.toast('Connect this action to POST /api/lab-tests.','warning');
  populate();renderEvidence();renderTimeline();
});
