document.addEventListener('DOMContentLoaded',async()=>{
  let patients=await apiRequest('/api/patients');const cases=await apiRequest('/api/cases'),tbody=document.getElementById('patientsTableBody'),search=document.getElementById('patientSearch'),status=document.getElementById('patientStatusFilter');
  const render=()=>{const term=search.value.toLowerCase(),filtered=patients.filter(p=>`${p.PatientID} ${p.Name} ${p.NIC} ${p.BHTNumber}`.toLowerCase().includes(term)&&(!status.value||(status.value==='deceased'?p.IsDeceased:!p.IsDeceased)));document.getElementById('patientCount').textContent=filtered.length;tbody.innerHTML=filtered.length?filtered.map(p=>`<tr><td class="record-id">PT-${p.PatientID}</td><td><strong>${UI.escapeHtml(p.Name)}</strong><br><small class="text-muted">${UI.escapeHtml(p.Address)}</small></td><td>${UI.escapeHtml(p.NIC||'Not recorded')}</td><td>${UI.escapeHtml(p.BHTNumber||'—')}</td><td>${p.Age} / ${p.Gender}</td><td>${UI.escapeHtml(p.PhoneNumber||'—')}</td><td>${UI.statusBadge(p.IsDeceased?'Deceased':'Living')}</td><td class="text-end"><button class="btn btn-sm btn-outline-primary view-patient" data-id="${p.PatientID}">View file</button></td></tr>`).join(''):UI.emptyRow(8);};
  [search,status].forEach(x=>x.addEventListener('input',render));document.getElementById('clearPatientFilters').onclick=()=>{search.value='';status.value='';render();};
  tbody.addEventListener('click',e=>{const b=e.target.closest('.view-patient');if(!b)return;const p=patients.find(x=>x.PatientID===Number(b.dataset.id)),linked=cases.filter(c=>c.PatientID===p.PatientID);document.getElementById('patientDrawerTitle').textContent=p.Name;document.getElementById('patientDrawerBody').innerHTML=`<div class="stat-inline mb-4"><div class="stat-pill"><span>Patient ID</span><strong>PT-${p.PatientID}</strong></div><div class="stat-pill"><span>Linked cases</span><strong>${linked.length}</strong></div><div class="stat-pill"><span>Record type</span><strong>${p.IsDeceased?'Deceased':'Clinical'}</strong></div></div>
  <section class="official-card mb-3"><div class="card-body"><h3 class="section-heading">Identification</h3><div class="row g-3"><div class="col-6"><small class="text-muted">NIC / Passport</small><div class="fw-semibold">${UI.escapeHtml(p.NIC||'Not recorded')}</div></div><div class="col-6"><small class="text-muted">BHT</small><div class="fw-semibold">${UI.escapeHtml(p.BHTNumber||'—')}</div></div><div class="col-12"><small class="text-muted">Address</small><div class="fw-semibold">${UI.escapeHtml(p.Address)}</div></div></div></div></section>
  <section class="official-card mb-3"><div class="card-body"><h3 class="section-heading">Next-of-kin</h3>${p.NextOfKin?.length?p.NextOfKin.map(n=>`<div class="border rounded p-3 mb-2"><strong>${UI.escapeHtml(n.Name)}</strong><br><span class="text-muted">${UI.escapeHtml(n.Relationship)} · ${UI.escapeHtml(n.PhoneNumber)}</span></div>`).join(''):'<p class="text-muted">No next-of-kin record.</p>'}</div></section>
  <section class="official-card"><div class="card-body"><h3 class="section-heading">Case history</h3>${linked.length?`<div class="timeline">${linked.map(c=>`<div class="timeline-item"><strong>CF-${c.CaseID} · ${UI.escapeHtml(c.CaseType)}</strong><span>${UI.formatDate(c.IncidentDate)} · ${UI.escapeHtml(c.Status)}</span></div>`).join('')}</div>`:'<p class="text-muted">No linked cases.</p>'}</div></section>`;bootstrap.Offcanvas.getOrCreateInstance(document.getElementById('patientDrawer')).show();});
  FormValidation.bindBootstrapValidation(document.getElementById('patientForm'),async(fd,form)=>{const r={Name:fd.get('Name').trim(),NIC:fd.get('NIC').trim(),Age:Number(fd.get('Age')),Gender:fd.get('Gender'),Address:fd.get('Address').trim(),PhoneNumber:fd.get('PhoneNumber').trim(),BHTNumber:fd.get('BHTNumber').trim(),IsDeceased:fd.get('IsDeceased')==='on',NextOfKin:fd.get('NOKName')?[{Name:fd.get('NOKName'),Relationship:fd.get('NOKRelationship'),PhoneNumber:fd.get('NOKPhone'),Address:fd.get('NOKAddress')}]:[]};const saved=await apiRequest('/api/patients',{method:'POST',body:r});patients.unshift(saved);render();form.reset();form.classList.remove('was-validated');bootstrap.Modal.getInstance(document.getElementById('patientModal')).hide();UI.toast(`Patient PT-${saved.PatientID} registered.`);});
  render();
});
