document.addEventListener('DOMContentLoaded',async()=>{
  let records=await apiRequest('/api/postmortems');const cases=(await apiRequest('/api/cases')).filter(c=>c.CaseType==='Postmortem');
  document.getElementById('pmCase').insertAdjacentHTML('beforeend',cases.map(c=>`<option value="${c.CaseID}">PM-${c.CaseID} — ${UI.escapeHtml(c.PoliceReferenceNo)}</option>`).join(''));
  const render=()=>document.getElementById('postmortemTable').innerHTML=records.length?records.map(pm=>`<tr><td class="record-id">PM-${pm.PostmortemID}</td><td class="record-id">CF-${pm.CaseID}</td><td>${UI.formatDate(pm.Date)}</td><td>${UI.escapeHtml(pm.Type)}</td><td>${UI.escapeHtml(pm.CauseOfDeath)}</td><td>${pm.DoctorID===17?'Dr. Kavinda Jayasinghe':'Dr. Nadeesha Perera'}</td><td>${UI.statusBadge(pm.Status||'Draft')}</td></tr>`).join(''):UI.emptyRow(7);
  const row=`<div class="row g-2 finding-row mb-2"><div class="col-md-3"><input class="form-control organ" placeholder="Organ / system"></div><div class="col-md-6"><input class="form-control observation" placeholder="Observation"></div><div class="col-md-2"><select class="form-select significance"><option>Relevant</option><option>Incidental</option><option>Normal</option><option>Pending</option></select></div><div class="col-md-1 d-grid"><button class="btn btn-outline-danger remove-finding" type="button">×</button></div></div>`;
  document.getElementById('addFinding').onclick=()=>document.getElementById('findingRows').insertAdjacentHTML('beforeend',row);
  document.getElementById('findingRows').onclick=e=>{if(e.target.closest('.remove-finding')&&document.querySelectorAll('.finding-row').length>1)e.target.closest('.finding-row').remove();};
  FormValidation.bindBootstrapValidation(document.getElementById('postmortemForm'),async(fd,form)=>{const findings=[...document.querySelectorAll('.finding-row')].map(r=>({Organ:r.querySelector('.organ').value,Observation:r.querySelector('.observation').value,Significance:r.querySelector('.significance').value})).filter(x=>x.Organ||x.Observation);const saved=await apiRequest('/api/postmortems',{method:'POST',body:{CaseID:Number(fd.get('CaseID')),DoctorID:Number(fd.get('DoctorID')),Date:fd.get('Date'),CauseOfDeath:fd.get('CauseOfDeath'),PMRDetails:fd.get('PMRDetails'),Type:fd.get('Type'),Status:'PM Report Pending',Findings:findings}});records.unshift(saved);render();form.reset();form.classList.remove('was-validated');bootstrap.Collapse.getOrCreateInstance(document.getElementById('postmortemEntry')).hide();UI.toast(`Postmortem PM-${saved.PostmortemID} saved.`);});
  render();
});
